apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}
        ports:
        - containerPort: 60000
          protocol: TCP
        command:
        - manager
        args:
        - --leader-elect
        resources:
            limits:
                cpu: {{ .Values.resources.limits.cpu}}
                memory: {{ .Values.resources.limits.memory}}
        env:
          - name: NAMESPACE
            value: {{ .Values.watch_namespace }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ .Release.Name }}
      restartPolicy: Always
      securityContext:
        runAsUser: 99
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: 30
