{{- $relname := .Release.Name -}}
{{- $relnamespace := .Release.Namespace -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $relname }}
{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $relname }}
  namespace: {{ . }}
rules:
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/finalizers
  - rediscluster/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis
  - redisclusters
  - redissentinels
  - redisreplications
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/status
  - rediscluster/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - secrets
  - pods/exec
  - pods
  - services
  - configmaps
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 'coordination.k8s.io'
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $relname }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $relname }}
subjects:
- kind: ServiceAccount
  name: {{ $relname }}
  namespace: {{ $relnamespace }}
{{- end }}
